### PR TITLE
Format source using prettier

### PR DESCRIPTION
**Pull request by anishkny**

### CODE REVIEW

**Comment by willclarktech** [comment]
Hi @anishkny, thanks for the PR, but what's the benefit of this?

**Comment by anishkny** [comment]
Mainly standardization with other open source projects.

When code looks similar to other pieces of code out there on Github, other tutorials etc, there is less cognitive load to process and the reader can focus on the actual meat of the code.

Also, [tabs are evil](http://tarantsov.com/hackers-coding-style-guide/why-tabs-should-be-avoided.html) 😝

**Comment by willclarktech** [comment]
Since this is a companion repo for a blog post on the Lisk blog, it's a higher priority that the code in these examples conforms to the [Lisk style](https://github.com/LiskHQ/eslint-config-lisk-base), so I'm going to close this.

I'd be interested to know if you're aware of any comprehensive stats about the use of prettier in open source projects though (including the extent to which they use options like `--use-tabs`, `--trailing-comma=all` etc). It might influence what we do in the Lisk style.

Also, complex code alignment is evil, and linting/continuous integration have come a long way since 2011!  😛

**Comment by anishkny** [comment]
https://hackernoon.com/what-javascript-code-style-is-the-most-popular-5a3f5bec1f6f

**Pull request closed without merging**
